TEAM_NAME_ALIASES = {
    # LCK
    'Gen.G': 'Gen.G Esports',
    'DRX': 'DRX',
    'Dplus KIA': 'Dplus KIA',
    'BNK FearX': 'FEARX',
    'FearX': 'FEARX',
    'BNK FEARX': 'FEARX',
    'BRO': 'OKSavingsBank BRION',
    'BRION': 'OKSavingsBank BRION',
    'OKSavingsBank BRO': 'OKSavingsBank BRION',
    'Kwangdong Freecs': 'Kwangdong Freecs',
    'HLE': 'Hanwha Life Esports',
    'NONGSHIM RED FORCE': 'Nongshim RedForce',
    'Nongshim Red Force': 'Nongshim RedForce',
    'NS RedForce': 'Nongshim RedForce',

    # LEC
    'Karmine Corp B': 'Karmine Corp Blue',
    'KC Blue': 'Karmine Corp Blue',
    'MAD Lions KOI': 'KOI',
    'Movistar KOI': 'KOI',
    'Giants': 'GIANTX',
    'NaVi': 'Natus Vincere',
    'Natus Vincere.LoL': 'Natus Vincere',
    'Team BDS': 'Team BDS',
    'Rogue': 'Rogue',

    # LPL (full sponsor names from API)
    'OMG': 'Oh My God',
    'TES': 'Top Esports',
    'TOPESPORTS': 'Top Esports',
    'WBG': 'Weibo Gaming',
    'WeiboGaming Faw Audi': 'Weibo Gaming',
    'WE': 'Team WE',
    "Xi'an Team WE": 'Team WE',
    'EDG': 'EDward Gaming',
    'SHANGHAI EDWARD GAMING HYCAN': 'EDward Gaming',
    'IG': 'Invictus Gaming',
    'JDG': 'JD Gaming',
    'Beijing JDG Intel Esports': 'JD Gaming',
    'LGD': 'LGD Gaming',
    'Hangzhou LGD Gaming': 'LGD Gaming',
    'LNG': 'LNG Esports',
    'Suzhou LNG Ninebot Esports': 'LNG Esports',
    'TT': 'ThunderTalk Gaming',
    'THUNDERTALKGAMING': 'ThunderTalk Gaming',
    'UP': 'Ultra Prime',
    'BLG': 'Bilibili Gaming',
    'BILIBILI GAMING DREAMSMART': 'Bilibili Gaming',
    'AL': "Anyone's Legend",
    'NIP': 'Ninjas in Pyjamas',
    'SHENZHEN NINJAS IN PYJAMAS': 'Ninjas in Pyjamas',
    'DCG': 'Deep Cross Gaming',

    # LCS / Americas
    'TL': 'Team Liquid',
    'Team Liquid Alienware': 'Team Liquid',
    'FLY': 'FlyQuest',
    'SR': 'Shopify Rebellion',
    'SEN': 'Sentinels',
    'LYON': 'LYON Gaming',
    'Disguised': 'Disguised',
    'Cloud9 Kia': 'Cloud9',
    'Cloud9': 'Cloud9',
    '100 Thieves': '100 Thieves',
    'Immortals Progressive': 'Immortals',
    'NRG Kia': 'NRG',
}
