# Generated by Django 5.2.1 on 2026-02-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0004_seed_tournaments'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='region',
            field=models.CharField(choices=[('europe', 'Europe'), ('north_america', 'North America'), ('china', 'China'), ('south_korea', 'South Korea'), ('apac', 'APAC')], default='europe', help_text='Regional division for the team', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='region',
            field=models.CharField(blank=True, choices=[('europe', 'Europe'), ('north_america', 'North America'), ('china', 'China'), ('south_korea', 'South Korea'), ('apac', 'APAC')], help_text='Primary region for this tournament', max_length=20, null=True),
        ),
    ]
