# Generated by Django 5.2.1 on 2026-02-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0005_team_region_tournament_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
