# Generated by Django 5.2.1 on 2026-02-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0006_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
